### ISSUE TITLE
Recommended XLA release is for CPU and does not find CUDA, however build fails with the GPU release of XLA

### ISSUE THREAD

**Issue by Ebanflo42** [LaurentMazare/xla-rs#12]
Note:
```
wget https://github.com/elixir-nx/xla/releases/download/v0.6.0/xla_extension-x86_64-linux-gnu-cpu.tar.gz
```
Downloads a CPU version of the XLA extension.

The build is successful but it was not surprising that we get the following XLA error:
```
   Compiling xla v0.1.6 (/home/ekadile/Projects/xla-rs)
    Finished release [optimized] target(s) in 2.33s
     Running `target/release/examples/nanogpt`
Error: xla error Could not find registered platform with name: "cuda". Available platform names are: Interpreter Host
disabled backtrace
```

However, if we unzip `xla_extension-aarch64-linux-gnu-cuda120.tar.gz` instead, I get a very long error message which boils down to the following:

```
  = note: /usr/bin/ld: skipping incompatible /home/ekadile/Projects/xla-rs/xla_extension/lib/libxla_extension.so when searching for -lxla_extension
          /usr/bin/ld: cannot find -lxla_extension: No such file or directory
          /usr/bin/ld: skipping incompatible /home/ekadile/Projects/xla-rs/xla_extension/lib/libxla_extension.so when searching for -lxla_extension
          collect2: error: ld returned 1 exit status
```

So it finds the so but says it is incompatible. Why? I have:

```
Driver Version: 530.30.02    CUDA Version: 12.1
```

Are the bindings sensitive to minor CUDA versions? This would be surprising. In fact, in the 0.5.1 release notes they say the requirement is specifically CUDA 12.1. I tried with 0.5.1 and the error I got caused my terminal to run out of lines, so I guess that is not the solution. 

Why does the build suppose that the cuda120 version of xla_extension is incompatible? I don't see how the examples could be run on the gpu without that.

**Comment by LaurentMazare** [comment]
Is it on purpose that you're using the `aarch64` version? As far as I know that's the arm64 build and not the Intel one which is `x86_64`.

**Comment by Ebanflo42** [comment]
Make sure CPU architecture matches XLA release :sweat_smile:
