### ISSUE TITLE
doc.rs build failed

### ISSUE THREAD

**Issue by alienscience** [LaurentMazare/xla-rs#2]
This looks like beginning of a very cool and useful project. Unfortunately, I lack the knowledge to contribute in any meaningful way -- just the first bug report.

There is no documentation for this project because the build on `docs.rs` failed: https://docs.rs/crate/xla/0.1.0/builds/787447

I know that it is very early days in the project, this issue is just to let you know in case you did not notice.

**Comment by LaurentMazare** [comment]
Thanks for pointing this out, indeed the build is broken on `docs.rs` as this requires the xla shared library to be installed which is not the case. Currently there isn't much documentation anyway but once there is, we'll probably use the same fix as in the pytorch bindings (deactivating the whole compilation when building the documentation).

**Comment by LaurentMazare** [comment]
This should be fixed now and the documentation should appear on [docs.rs/xla](https://docs.rs/xla/latest/xla/). There is almost no documentation at the moment but it's certainly on the list to add some once things have become a bit mor estable.

**Comment by LaurentMazare** [comment]
Closing this now that docs are populated properly.
