### ISSUE TITLE
Import jax functions?

### ISSUE THREAD

**Issue by aseyboldt** [LaurentMazare/xla-rs#3]
That you for the library, this looks great!

I was wondering if it would be possible to import existing jax functions and run them from rust.
So similar to the example in the jax repo that is run from C++:
https://github.com/google/jax/blob/main/examples/jax_cpp/main.cc

**Comment by LaurentMazare** [comment]
Right, I just added some wrappers to be able to load HLO files and execute them. You can see an equivalent of the C++ example in [examples/load_hlo.rs](https://github.com/LaurentMazare/xla-rs/blob/main/examples/load_hlo.rs). Currenty this only supports loading the text format but I'll add support for the protobuf version soon.

**Comment by aseyboldt** [comment]
That was fast :-)
Works just fine, thank you!
