### ISSUE TITLE
Does it work with PJRT plugins?

### ISSUE THREAD

**Issue by jczaja** [LaurentMazare/xla-rs#7]
Hi,

I can see this project does link dynamically to xla_extension.so , but OpenXLA is supporting plugin mechanism via PJRT (https://github.com/openxla/openxla-pjrt-plugin) . Does this project supports working with OpenXLA plugins (dynamically loaded shared objects that are implementing PJRT API) ?

Thanks for developing this very interesting project!

**Comment by LaurentMazare** [comment]
I don't know much about pjrt plugins and didn't give this a try so no real clue I'm afraid.

**Comment by jczaja** [comment]
Ok, thanks for answer
